# 기본 Active Profile 정의
# 변경시는 실행시점에 별도 인자값으로 정의
# ex) --spring.profiles.active=local,mysql-local-database
spring:
  profiles:
    active: local,h2-local-db

  datasource:
    initialize: true

logging:
  config: classpath:logback-console.xml

server:
  port: 8080
  display-name: jpa
  session:
    timeout: 3600

---
spring:
  profiles: mysql-local-db
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpa?useUnicode=true&amp;characterEncoding=utf8
    username: jpa
    password: jpa
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: validate

---
spring:
  profiles: h2-local-db
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:./h2db/jpa;AUTO_SERVER=TRUE
    username: sa
    password: sa
    max-active: 10
  secondDatasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:./h2db/jpa-datasources;AUTO_SERVER=TRUE
    username: sa
    password: sa
    max-active: 10
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: create
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
        hbm2ddl:
          import_files: /scripts/user.sql
  h2:
    console:
      enabled: true
      path: /console

---
spring:
  profiles: h2-in-memory-db
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:jpa;DB_CLOSE_DELAY\=-1
    username: sa
    password:
  secondDatasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:jpa-datasources;DB_CLOSE_DELAY\=-1
    username: sa
    password:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /console
---

